### ISSUE TITLE
時計島ギミック作動/停止時の演出強化

### ISSUE THREAD

**Issue by Syareene** [Syareene/TUSB_TimeLimit#2]
# 概要
みすぼらしいからもっとぽいものにしようよ

# 内容
任せた

**Comment by Syareene** [comment]
あ、これ同じ場所にあるclock2と3にも適応しないと今は第一→第二の演出が強化されただけになってると思う
(やってる途中だったら申し訳ない)

**Comment by FreyCielu** [comment]
やってる途中です( ᐛ)

**Comment by FreyCielu** [comment]
多分これでいいと思います
負荷的に軽くできそうなやつあったら誰かしてください( ᐛ)
